app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/





// Registration routes...
// Route::get('auth/register', 'Auth\AuthController@getRegister');
// Route::post('auth/register', 'Auth\AuthController@postRegister');


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'PageController@index');
    Route::get('/about','PageController@about');
    Route::get('/contact','PageController@contact');


    //Post Routes
    Route::get('/post/{post}','ArticleController@show')->where('post','[a-zA-Z0-9-\']+');

    //Tags Routes
    Route::get('/tags/{tag}','TagController@index')->where('tag','[a-zA-Z]+');



    // Admin routes
    // admin.panel
    Route::get('admin/panel', 	['as' => 'admin.panel',
    							'uses'=>'AdminController@index']);
    //admnin.post.all
    Route::get('admin/post/all',	['as' => 'admin.post.all',
    								'uses' => 'AdminController@showAllPost']);

    //admin.post.create
    Route::get('admin/post/create', ['as' => 'admin.post.create',
    								'uses' => 'AdminController@showCreate']);
    Route::post('admin/post/create', ['as' => 'admin.post.create',
    								'uses' => 'AdminController@createPost']);
    
    //admin.post.edit
    Route::get('admin/post/{title}/edit',  ['as'=>'admin.post.edit',
    										'uses'=>'AdminController@showEdit'])
    										->where('title','[a-zA-Z0-9-\']+');
    Route::post('admin/post/{title}/edit',  ['as'=>'admin.post.edit',
    										'uses'=>'AdminController@updatePost'])
    										->where('title','[a-zA-Z0-9-\']+');
    //admin.post.delete
    Route::get('admin/post/{title}/delete', ['as'=>'admin.post.delete',
    										'uses'=>'AdminController@deletePost'])
    										->where('title','[a-zA-Z0-9-\']+');
    //admin.post.search
    Route::post('admin/post/search',['as'=>'admin.post.search',
    										'uses'=>'AdminController@searchPosts'])
    										->where('title','[a-zA-Z0-9-\']+');

    Route::post('admin/post/view/{token}','AdminController@viewPost');
    //admin.post.messages
    Route::get('admin/messages',['as'=>'admin.messages',
    							'uses'=>'AdminController@showMessages']);
    //admin.user.all
    Route::get('admin/user/all',['as'=>'admin.user.all',
    							'uses'=>'AdminController@allUsers']);
    //admin.user.create
    Route::get('admin/user/create',['as'=>'admin.user.create',
    								'uses'=>'AdminController@showCreateUser']);

    Route::get('admin/image/upload',['as'=>'admin.image.upload',
                                     'uses'=>'AdminController@showForm']);

    Route::post('admin/image/upload',['as'=>'admin.image.upload',
                                     'uses'=>'ImageController@uploadImage']);
    Route::post('uploads/image/all',['as'=>'uploads.images.all',
                                     'uses'=>'ImageController@getAllImages']);
    Route::get('uploads/image/{id}',['as'=>'uploads.images',
                                      'uses'=>'ImageController@getImage']);





	// Authentication routes...
	Route::get('admin/login', ['as'=>'admin.login',
								'uses'=>'Auth\AuthController@getLogin']);
	Route::post('admin/login', 'Auth\AuthController@postLogin');
	Route::get('admin/logout', function(){
		if(Auth::check())
		{
			Auth::logout();
		}
		return redirect("admin/login");
	});
});

app/Article.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id','tag_id','title', 'excerpt', 'display_image', 'content', 'publish_date'
    ];

    protected $dates = ['publish_date','created_at','updated_at'];

    public static $createRules = array(
        'title'         =>  'required|unique:articles|max:255|regex:/^[a-z\d ]+$/i',
        'excerpt'       =>  'required|max:500',
        'content'       =>  'required',
        'publish_date'  =>  'required|date|after:yesterday',
        'display_image' =>  'required',
        'tag_id'        =>  'required'
    );
    public static $editRules = array(
        'title'         =>  'required|max:255|regex:/^[a-z\d ]+$/i',
        'excerpt'       =>  'required|max:500',
        'content'       =>  'required',
        'publish_date'  =>  'required|date',
        'display_image' =>  'required',
        'tag_id'        =>  'required|digits:1'
    );
    
    public static $messages = array(
        'title.unique'          =>  'This title has already been used',
        'title.regex'           =>  'Title can only contain Alphabets, Numbers and Spaces',
        'publish_date.after'    =>  'Article can only be published in current or future dates',
    );

    public function getPublishDateAttribute($value)
    {
    	$date = new Carbon($value);
    	return $date->format('Y-m-d');
    }

    public function getShortPublishedMonth()
    {
        $date = new Carbon($this->publish_date);
        return $date->format('M');
    }

    /*public function getContentAttribute($value)
    {
        $content = \Markdown::parse($value);
        return $content;
    }*/

    public function getParsedContentAttribute()
    {
        $content = \Markdown::parse($this->content);
        return $content;
    }

    public function getPublishDateStampAttribute()
    {
        $date = new Carbon($this->publish_date);
        return $date->format('Y-m-d');
    }

    public function getPublishDateCarbonAttribute()
    {
        $date = new Carbon($this->publish_date);
        return $date;
    }


    public function scopeLatest($query)
    {
        return $query->orderBy('publish_date','desc');
    }


    /**
     * Article Belongs to a User
     * 1:M
     */
    
    public function user()
    {
    	return $this->belongsTo('App\User');
    }

    /**
     * Article belongs to a tag
     * 1:M
     */
    
    public function tag()
    {
    	return $this->belongsTo('App\Tag');
    }

    public function getUrlSafeTitle(){ 
        return preg_replace('/\s+/', '-', $this->title);
    }

    private function getUrlUnsafeTitle()
    {
        return preg_replace('/-/',' ',$this->title);
    }

    public static function urlSafeTitle($title)
    {
        return preg_replace('/\s+/', '-', $this->title);
    }

    public static function urlUnsafeTitle($title)
    {
        return preg_replace('/-/',' ',$title);
    }
}

resources/views/admin/post/create.blade.php
@extends("admin.master.layout")

@section('styles')
{{Html::style('css/libs/dropzone.css')}}
@endsections

@section('top-scripts')
{{Html::script('js/libs/autosize.min.js')}}
{{Html::script('js/libs/dropzone.js')}}
@endsection

@section('main-content')
{!!Form::open(array('route'=>'admin.post.create','name'=>'dataForm'))!!}
<h2>Create a new post</h2>
<div class="form-group">
{{Form::label('title','Title')}}
{{Form::text('title',old('name'))}}
@if($errors->has('title'))
		<p class="error">{{$errors->first('title')}}</p>
@endif
</div>
<div class="form-group">
{{Form::label('excerpt','Excerpt')}}
{{Form::text('excerpt')}}
@if($errors->has('excerpt'))
	<p class="error">{{$errors->first('excerpt')}}</p>
@endif
</div>
<div class="form-group">
{{Form::label('publish_date','Publish Date')}}
{{Form::date('publish_date',Carbon\Carbon::now())}}
@if($errors->has('publish_date'))
	<p class="error">{{$errors->first('publish_date')}}</p>
@endif	
</div>
<div class="form-group">
{{Form::label('tag_id','Category')}}
<select id="tag_id" name="tag_id">
	@foreach ($tags as $tag)
		<option value="{{$tag->id}}">{{$tag->name}}</option>
	@endforeach
</select>
@if($errors->has('category'))
	<p class="error">{{$errors->first('tag_id')}}</p>
@endif
</div>
<div class="form-group">
{{Form::label('display_image','Display Image')}}
{{Form::number('display_image')}}
@if($errors->has('display_image'))
	<p class="error">{{$errors->first('display_image')}}</p>
@endif
</div>
<div class="form-group">
{{Form::label('content','Content')}}
@include('admin.partials.content-menu')
{{Form::textarea('content')}}
@if($errors->has('content'))
	<p class="error">{{$errors->first('content')}}</p>
@endif
</div>
<div class="form-group">
{{Form::button('View',['class'=>'view'])}}
{{Form::submit('Create')}}
</div>
{!!Form::close()!!}
<div id="overlay">
</div>
<div class="image-box">
	<div class="image-box-header">
		<h2 class="image-box-header-title">
			Image Picker
		</h2>
		<span class="image-box-header-close">
			<i class="image-box-header-close-button fa fa-times"></i>
		</span>
	</div>
	<div class="image-box-tabs">
		<span class="image-box-tab image-box-selected">Pictures</span>
		<span class="image-box-tab">Upload</span>
	</div>
	<div class="pictures">

	</div>
	<div class="upload" id="upload">
		{{Form::open(['route'=>'admin.image.upload','class'=>'dropzone','id'=>'upload-file'])}}
		<div class="fallback">
		    <input name="file" type="file" multiple />
		</div>
		{{Form::close()}}
	</div>
</div>
@endsection

@section('bottom-scripts')
{{Html::script('js/view-handler.js')}}
{{Html::script('js/sticky-content-menu.js')}}
<script>
function _insertAtCaret(element, text) {
    var caretPos = element[0].selectionStart,
        currentValue = element.val();

    element.val(currentValue.substring(0, caretPos) + text + currentValue.substring(caretPos));
  document.getElementsByName("content")[0].selectionStart = caretPos + text.length;
  document.getElementsByName("content")[0].selectionEnd = caretPos + text.length;
}
var dataTypes = {
	h1 		: 	"\n#Heading One",
	h2 		: 	"\n##Heading Two",
	h3 		: 	"\n###Heading Three",
	h4 		: 	"\n####Heading Four",
	h5 		: 	"\n#####Heading Five",
	h6 		: 	"\n######Heading Six",
	b 		: 	"**bold text here**",
	i 		: 	"*italic text here*",
	u   	: 	"<u>underlined text here</u>",
	img 	: 	' ![alternate text](http://website.com "Image title text") ',
	a 		: 	' [link text](http://example.com/ "title text") ',
	code 	: 	'\n```\n//code goes here\n```',
	olist 	: 	'\n1. item one \n2. item two \n3. item 3',
	ulist 	: 	'\n* item one \n* item two \n* item 3',
	sep 	: 	'\n_________________________\n',
};
$('.content-menu-item').click(function(){

	var sel = $(this).attr('data-type');
	if(sel in dataTypes){
		if(sel==="img"){
			$('#overlay').fadeIn();
			$('.image-box').fadeIn();
			getAllImages(sel);
		}else{
			_insertAtCaret($('textarea[name=content]'),dataTypes[sel]);
		}
	}
});


var overlay = $('#overlay');
var imagebox = $('.image-box');
imagebox.hide();
overlay.hide();
overlay.click(function(){
	$(this).fadeOut();
	imagebox.fadeOut();
});
//onclick of imagebox close button
$('.image-box-header-close-button').click(function(){
	imagebox.fadeOut();
	overlay.fadeOut();
});
//tabs switching
$('.image-box-tab').click(function(){
	$('.image-box-tab').removeClass('image-box-selected');
	$(this).addClass('image-box-selected');
	if($(this).html()=="Pictures"){
		$('.pictures').show();
		$('.upload').hide();
	}else if($(this).html()=="Upload"){
		$('.pictures').hide();
		$('.upload').show();
	}
});

//Onclick of display image input box
$('#display_image').click(function(){
	overlay.fadeIn();
	imagebox.fadeIn();
	getAllImages("disp");
});


function getAllImages(to)
{
	var base_url = "http://"+window.location.host;
	var all_image_url = base_url+"/uploads/image/all";
	var xcsrf = $("meta[name=X-CSRF-TOKEN]").attr("content");
	$.ajax({
		url : all_image_url,
		type : "post",
		data : {'_token':xcsrf},
		success : function(data) {
			if(data.length != 0) 
			{
				var html = "";
				$.each(data,function(index,value){
					html += "<span class='box'><img class='box-bg' data-id='"+value.id+"'' onclick='getImg(this,\""+to+"\")' src='"+base_url+"/uploads/image/"+value.id+"'></span>";
				});
				$('.pictures').html(html);
			}
		}
	});
}

function getImg(from,to)
{
	if(to == "disp") {
		var id = $(from).attr('data-id');
		$("#display_image").val(id);
	}else if(to == "img"){
		var src = $(from).attr('src');
		_insertAtCaret($('textarea[name=content]'),"![alternate text]("+src+" \"Image title text\")");
	}
	imagebox.fadeOut();
	overlay.fadeOut();
}
Dropzone.options.uploadFile = {
    paramName: "file", // The name that will be used to transfer the file
    maxFilesize: 3, // MB
    acceptedFiles:"image/*",	
};
</script>
@endsection

resources/views/admin/post/edit.blade.php
@extends("admin.master.layout")

@section('top-scripts')
{{Html::script('js/libs/dropzone.js')}}
{{Html::script('js/libs/autosize.min.js')}}
@endsection

@section('styles')
{{Html::style('css/libs/dropzone.css')}}
@endsection

@section('main-content')
@if (Session::has('message'))
	<div class="flash-message">{{Session::get('message')}}</div>
@endif
<!-- <div class="flash-message">This post has been updated!</div> -->
{!! Form::model($article, ['route' => array('admin.post.edit', $article->getUrlSafeTitle()),'name'=>'dataForm']) !!} 
<h2>Edit : {{ Form::text('title',old('title')) }}</h2>
@if($errors->has('title'))
		<p class="error">{{$errors->first('title')}}</p>
@endif
<div class="form-group">
	{{Form::label('publish_date','Publish Date')}}
	{{Form::date('publish_date', old('publish_date'))}}
	@if($errors->has('publish_date'))
		<p class="error">{{$errors->first('publish_date')}}</p>
	@endif
</div>
<div class="form-group">
	{{Form::label('tag_id','Category')}}
	<select id="tag_id" name="tag_id">
	@foreach($tags as $tag)
		@if($article->tag->id == $tag->id)
			<option value="{{$tag->id}}" SELECTED>{{$tag->name}}</option>
		@else
			<option value="{{$tag->id}}">{{$tag->name}}</option>
		@endif
	@endforeach	
	</select>
</div>
<div class="form-group">
	{{Form::label('display_image','Display Image')}}
	{{Form::text('display_image', old('display_image'))}}
	@if($errors->has('display_image'))
		<p class="error">{{$errors->first('display_image')}}</p>
	@endif
</div>
<div class="form-group">
	{{Form::label('excerpt','Excerpt')}}
	{{Form::text('excerpt', old('excerpt'))}}
	@if($errors->has('excerpt'))
		<p class="error">{{$errors->first('excerpt')}}</p>
	@endif
</div>
<div class="form-group">
	{{Form::label('content','Content')}}
	@include('admin.partials.content-menu')
	{{Form::textarea('content', old('content'))}}
	@if($errors->has('content'))
		<p class="error">{{$errors->first('content')}}</p>
	@endif
</div>
<div class="form-group">
	{{Form::button('View',['class'=>'view'])}}
	{{Form::submit('Update')}}
	{{Form::button('Delete',['class'=>'delete'])}}
</div>
{!! Form::close() !!}
<div id="overlay">
</div>
<div class="image-box">
	<div class="image-box-header">
		<h2 class="image-box-header-title">
			Image Picker
		</h2>
		<span class="image-box-header-close">
			<i class="image-box-header-close-button fa fa-times"></i>
		</span>
	</div>
	<div class="image-box-tabs">
		<span class="image-box-tab image-box-selected">Pictures</span>
		<span class="image-box-tab">Upload</span>
	</div>
	<div class="pictures">

	</div>
	<div class="upload" id="upload">
		{{Form::open(['route'=>'admin.image.upload','class'=>'dropzone','id'=>'upload-file'])}}
		<div class="fallback">
		    <input name="file" type="file" multiple />
		</div>
		{{Form::close()}}
	</div>
</div>
@endsection

@section('bottom-scripts')
{{Html::script('js/view-handler.js')}}
{{Html::script('js/sticky-content-menu.js')}}
<script>
function _insertAtCaret(element, text) {
    var caretPos = element[0].selectionStart,
        currentValue = element.val();

    element.val(currentValue.substring(0, caretPos) + text + currentValue.substring(caretPos));
  document.getElementsByName("content")[0].selectionStart = caretPos + text.length;
  document.getElementsByName("content")[0].selectionEnd = caretPos + text.length;
}
var dataTypes = {
	h1 		: 	"\n#Heading One",
	h2 		: 	"\n##Heading Two",
	h3 		: 	"\n###Heading Three",
	h4 		: 	"\n####Heading Four",
	h5 		: 	"\n#####Heading Five",
	h6 		: 	"\n######Heading Six",
	b 		: 	"**bold text here**",
	i 		: 	"*italic text here*",
	u   	: 	"<u>underlined text here</u>",
	img 	: 	' ![alternate text](http://website.com "Image title text") ',
	a 		: 	' [link text](http://example.com/ "title text") ',
	code 	: 	'\n```\n//code goes here\n```',
	olist 	: 	'\n1. item one \n2. item two \n3. item 3',
	ulist 	: 	'\n* item one \n* item two \n* item 3',
	sep 	: 	'\n_________________________\n',
};
$('.content-menu-item').click(function(){

	var sel = $(this).attr('data-type');
	if(sel in dataTypes){
		if(sel==="img"){
			$('#overlay').fadeIn();
			$('.image-box').fadeIn();
			getAllImages(sel);
		}else{
			_insertAtCaret($('textarea[name=content]'),dataTypes[sel]);
		}
	}
});


var overlay = $('#overlay');
var imagebox = $('.image-box');
imagebox.hide();
overlay.hide();
overlay.click(function(){
	$(this).fadeOut();
	imagebox.fadeOut();
});
//onclick of imagebox close button
$('.image-box-header-close-button').click(function(){
	imagebox.fadeOut();
	overlay.fadeOut();
});
//tabs switching
$('.image-box-tab').click(function(){
	$('.image-box-tab').removeClass('image-box-selected');
	$(this).addClass('image-box-selected');
	if($(this).html()=="Pictures"){
		$('.pictures').show();
		$('.upload').hide();
	}else if($(this).html()=="Upload"){
		$('.pictures').hide();
		$('.upload').show();
	}
});

//Onclick of display image input box
$('#display_image').click(function(){
	overlay.fadeIn();
	imagebox.fadeIn();
	getAllImages("disp");
});


function getAllImages(to)
{
	var base_url = "http://"+window.location.host;
	var all_image_url = base_url+"/uploads/image/all";
	var xcsrf = $("meta[name=X-CSRF-TOKEN]").attr("content");
	$.ajax({
		url : all_image_url,
		type : "post",
		data : {'_token':xcsrf},
		success : function(data) {
			if(data.length != 0) 
			{
				var html = "";
				$.each(data,function(index,value){
					html += "<span class='box'><img class='box-bg' data-id='"+value.id+"'' onclick='getImg(this,\""+to+"\")' src='"+base_url+"/uploads/image/"+value.id+"'></span>";
				});
				$('.pictures').html(html);
			}
		}
	});
}

function getImg(from,to)
{
	if(to == "disp") {
		var id = $(from).attr('data-id');
		$("#display_image").val(id);
	}else if(to == "img"){
		var src = $(from).attr('src');
		_insertAtCaret($('textarea[name=content]'),"![alternate text]("+src+" \"Image title text\")");
	}
	imagebox.fadeOut();
	overlay.fadeOut();
}

Dropzone.options.uploadFile = {
    paramName: "file", // The name that will be used to transfer the file
    maxFilesize: 3, // MB
    acceptedFiles:"image/*",	
};
</script>
@endsection

resources/views/admin/post/showall.blade.php
@extends('admin.master.layout')


@section('main-content')
<h2>All Articles</h2>
<div class="search">
	<input type="text" id="search" name="search">
	<label for="search">Search</label>
	<ul class="search-results">
		<li class="result-item"><a href="#">result</a></li>
		<li class="result-item"><a href="#">Another item</a></li>
		<li class="result-item"><a href="#">Another item</a></li>
		<li class="result-item"><a href="#">Another item</a></li>
		<li class="result-item"><a href="#">Another item</a></li>
	</ul>
</div>

@if(isset($articles))
    @if ($articles->count())
    	<?php $i = 0; ?>
        @foreach ($articles as $article)
            @if ($i%2 == 0)
                <div class="post-row">
            @endif
            	<div class="post">
            		<div class="post-date">
            			<p>{{$article->publish_date_carbon->day}}</p>
            			<p>{{$article->getShortPublishedMonth()}}</p>
            			<p>{{$article->publish_date_carbon->year}}</p>
            		</div>
            		<div class="post-content">
            			<h3>{{$article->title}}</h3>
            			<p>{{$article->excerpt}}</p>
            		</div>
            		<div class="post-controls">
            			<a href="{{url('/post/'.$article->getUrlSafeTitle())}}">View</a>
						<a href="{{url('/admin/post/'.$article->getUrlSafeTitle().'/edit')}}">Edit</a>
						<a href="{{url('/admin/post/'.$article->getUrlSafeTitle().'/delete')}}">Delete</a>
					</div>
            	</div>
            @if ($i%2 != 0 || $articles->count()==1)
                </div>
            @endif
            <?php $i++ ?>
        @endforeach
    @else
        <h1 align="center" style="opacity:0.5; font-weight: 600;">No Posts to Display</h1>
    @endif
    @if($articles->hasPages())
        <div align="center">
        {{ $articles->render() }}
        </div>
    @endif
@endif

@section('bottom-scripts')
<script type="text/javascript">
var search_input = $("#search");
var search_results = $(".search-results");
var base_url = "http://"+window.location.host;
var search_url = base_url+"/admin/post/search";
var xcsrf = $("meta[name=X-CSRF-TOKEN]").attr("content");
var prev = 0;
search_input.keyup(function(e){
	if(search_input.val().length != 0)
	{
		$.ajax({
			url : search_url,
			type : "post",
			data : {'search':search_input.val(),'_token':xcsrf},
			success : function(data){
				if(data.length != 0)
				{
					var html = "";
					for(var i=0;i<data.length;i++){
						var title = data[i].title;
						html += '<li class="result-item"><a href="'+base_url+'/admin/post/'+title.replace(/\s+/g, '-').toLowerCase()+'/edit">'+title+"</a></li>";
					}
					search_results.html("");
					search_results.html(html);
					search_results.slideDown();
				}else{
					search_results.slideUp();
				}
				
			}
		});
			
	}else{
		search_results.slideUp();
	}
});
</script>
@endsection

@endsection

resources/views/admin/post/view.blade.php
@extends('public.master.layout')
@section('title')
{{$article->title}} - DeveloperNish  
@endsection

@section('description')
{{$article->excerpt}}
@endsection

@section('top-scripts')
	<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/7.3/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
@endsection

@section('styles')
	{{ Html::style('css/themes/tomorrow-night-eighties.css') }}
@endsection

@section('main-content')
<article class="single-post">
    <header class="single-post-header">
        <h1 class="single-post-title">{{ $article->title }}</h1>
        <div class="single-post-meta">
            <ul class="metas">
                <li class="date"><a href="#">{{ $article->publish_date_stamp }}</a></li>
                <li class="tag"><a href="{{ url('/tags/'.$article->tag->name) }}">{{ $article->tag->name }}</a></li>
            </ul>
        </div>
        <p class="single-post-excerpt">
        {{ $article->excerpt }}
        </p>
    </header>
    <div class="single-post-image">
        <img src="/uploads/image/{{ $article->display_image }}" alt="{{ $article->title }}" title="{{ $article->title }}">
    </div>
    <div class="single-post-body">
    	{!! $article->parsed_content !!}
    </div>
</article>

    
@endsection